spring:
  application:
    name: account-service

  config:
    activate:
      on-profile: default

  # DB Config
  datasource:
    url: jdbc:postgresql://streamcore-postgres:5433/STreamCore
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  # JPA Config
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server Config
server:
  port: 8081
  servlet:
    context-path: /api/v1


# OpenAPI Config
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method